name: 'Azure Web App Deployment'
description: 'Deploys a web application to an Azure App Service'
inputs:
  connection-type:
    description: 'Service connection type to use to deploy the Web App. PublishProfile for using Visual Studio created Publish profile, otherwise enter AzureRM'
    required: true
    default: 'AzureRM'
  azure-client-id:
    description: 'The Client ID of the service principal to use when connecting to Azure (Only relevant when connection-type is set to AzureRM)'
    required: false
  azure-client-secret:
    description: 'The Client Secret of the service principal to use when connecting to Azure (Only relevant when connection-type is set to AzureRM)'
    required: false
  publish-profile-path:
    description: 'Path to publish profile (Only relevant when connection-type is set to PublishProfile)'
    required: false
  publish-profile-password:
    description: 'It is recommended to retrieve this value from a secret (Only relevant when connection-type is set to PublishProfile)'
    required: false
  webapp-kind: # this may not be needed, think it only powers the webapp-name dropdown
    description: 'Possible values: webApp, webAppLinux, webAppContainer, functionApp, functionAppLinux, functionAppContainer, apiApp, mobileApp (Only relevant when connection-type is set to AzureRm)'
    required: false
    default: 'webApp'
  webapp-name:
    description: 'App Service Name (Only relevant when connection-type is set to AzureRM'
    required: false
  deploy-to-slot-or-ase:
    description: 'Deploy to slot or App Service Environment (Only relevant when connection-type is set to AzureRM)'
    required: false
    default: 'false'
  resource-group-name: # this may not be needed
    description: 'Name of Azure Resource Group that the App Service belongs to'
    required: false
  slot-name:
    description: 'Name of slot to deploy to (Only relevant when connection-type is set to AzureRM and deploy-to-slot-or-ase is true)'
    required: false
    default: 'production'
  docker-namespace:
    description: 'A globally unique top-level domain name for your specific registry or namespace.'
    required: false
  docker-repository:
    description: 'Name of the repository where the container images are stored.'
    required: false
  docker-image-tag:
    description: 'Tags are optional, it is the mechanism that registries use to give Docker images a version.'
    required: false
  virtual-application:
    description: 'Specify the name of the Virtual application that has been configured in the Azure portal. The option is not required for deployments to the App Service root.'
    required: false
  package:
    description: 'File path to the package or a folder containing app service contents generated by MSBuild or a compressed zip or war file'
    required: false
    default: '**/*.zip'
  runtime-stack:
    description: 'Enter the framework and version (for linux web apps only)'
    required: false
  runtime-stack-function:
    description: 'Enter the framework and version (for linux function apps only)'
    required: false
  startup-command:
    description: 'Enter the start up command. For ex: dotnet exec filename.dll'
    required: false
  script-type:
    description: 'Customize the deployment by providing a script that will run on the Azure App service once the task has completed the deployment successfully . For example restore packages for Node, PHP, Python applications.'
    required: false
  inline-script:
    description: 'You can provide your deployment commands here, one per line'
    required: false
  script-path:
    description: 'Deployment script path'
    required: false
  web-config-parameters:
    description: 'A standard Web.config will be generated and deployed to Azure App Service if the application does not have one. The values in web.config can be edited and vary based on the application framework. For example for node.js application, web.config will have startup file and iis_node module values. This edit feature is only for the generated web.config'
    required: false
  app-settings:
    description: 'Edit web app application settings following the syntax -key value . Value containing spaces should be enclosed in double quotes .Example: -Port 5000 -RequestTimeout 5000 -WEBSITE_TIME_ZONE "Eastern Standard Time"'
    required: false
  configuration-settings:
    description: 'Edit web app configuration settings following the syntax -key value. Value containing spaces should be enclosed in double quotes. Example: -phpVersion 5.6 -linuxFxVersion: node|6.11'
    required: false
  use-web-deploy:
    description: 'If false we will auto-detect the best deployment method based on your app type, package format and other parameters. Select the option to view the supported deployment methods and choose one for deploying your app.'
    required: false
    default: 'false'
  deployment-type:
    description: 'Options are: webDeploy, zipDeploy, runFromZip'
    required: false
    default: 'webDeploy'
  take-app-offline:
    description: 'Select the option to take the Azure App Service offline by placing an app_offline.htm file in the root directory of the App Service before the sync operation begins. The file will be removed after the sync operation completes successfully.'
    required: false
    default: 'true'
  setparameters-file:
    description: 'location of the SetParameters.xml file to use.'
    required: false
  remove-additional-files:
    description: 'Select the option to delete files on the Azure App Service that have no matching files in the App Service package or folder.<br /><br />Note: This will also remove all files related to any extension installed on this Azure App Service. To prevent this, select 'Exclude files from App_Data folder' checkbox.'
    required: false
    default: 'true'
  exclude-files-from-appdata:
    description: 'Select the option to prevent files in the App_Data folder from being deployed to/ deleted from the Azure App Service.'
    required: false
    default: 'true'
  additional-arguments:
    description: 'Additional Web Deploy arguments following the syntax -key:value .<br />These will be applied when deploying the Azure App Service. Example: -disableLink:AppPoolExtension -disableLink:ContentExtension.<br />For more examples of Web Deploy operation settings, refer to  [this](https://go.microsoft.com/fwlink/?linkid=838471).'
    required: false
    default: '-retryAttempts:6 -retryInterval:10000'
  rename-files:
    description: 'Select the option to enable msdeploy flag MSDEPLOY_RENAME_LOCKED_FILES=1 in Azure App Service application settings. The option if set enables msdeploy to rename locked files that are locked during app deployment'
    required: false
    default: 'true'
  xml-transformation:
    description: 'The config transforms will be run for `*.Release.config` and `*.<EnvironmentName>.config` on the `*.config file`.<br/> Config transforms will be run prior to the Variable Substitution.<br/>XML transformations are supported only for Windows platform.'
    required: false
    default: 'false'
  xml-variable-substitution:
    description: 'Variables defined in the build or release pipelines will be matched against the 'key' or 'name' entries in the appSettings, applicationSettings, and connectionStrings sections of any config file and parameters.xml. Variable Substitution is run after config transforms. <br/><br/> Note: If same variables are defined in the release pipeline and in the environment, then the environment variables will supersede the release pipeline variables.<br/>'
    required: false
    default: 'false'
  json-files:
    description: 'Provide new line separated list of JSON files to substitute the variable values. Files names are to be provided relative to the root folder. <br/> To substitute JSON variables that are nested or hierarchical, specify them using JSONPath expressions. <br/> <br/> For example, to replace the value of ConnectionString in the sample below, you need to define a variable as Data.DefaultConnection.ConnectionString in the build or release pipeline (or release pipelines environment). <br/> {<br/>&nbsp;&nbsp;\"Data\": {<br/>&nbsp;&nbsp;&nbsp;&nbsp;\"DefaultConnection\": {<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\"ConnectionString\": \"Server=(localdb)\\SQLEXPRESS;Database=MyDB;Trusted_Connection=True\"<br/>&nbsp;&nbsp;&nbsp;&nbsp;}<br/>&nbsp;&nbsp;}<br/> }<br/> Variable Substitution is run after configuration transforms. <br/><br/> Note: pipeline variables are excluded in substitution.'
    required: false

outputs:
  app-service-url:
    description: 'Application URL of the selected App Service.'

runs:
  using: 'node12'
  main: 'dist/index.js'