name: 'Azure Web App Deployment'
description: 'Deploys a web application to an Azure App Service'
author: 'dylan-smith'
inputs:
  webapp-name:
    description: 'App Service Name (Only relevant when connection-type is set to AzureRM'
    required: false

outputs:
  app-service-url:
    description: 'Application URL of the selected App Service.'

runs:
  using: 'node12'
  main: 'dist/index.js'